In [ ]:
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules, fpgrowth
pd.set_option('display.max_columns', None)

df = pd.read_csv(r"sample_data/test.csv")


#Idade(Age)
df["Age_14_15"] = df["Age"].apply(lambda x: 1 if 14 <= x <= 15 else 0)
df["Age_16_17"] = df["Age"].apply(lambda x: 1 if 16 <= x <= 17 else 0)
df["Age_18"] = df["Age"].apply(lambda x: 1 if x == 18 else 0)
df.drop(columns=["Age"], inplace=True)

#Ano(Grade)
df["Grade_9"]  = df["Grade"].apply(lambda x: 1 if x == 9 else 0)
df["Grade_10"] = df["Grade"].apply(lambda x: 1 if x == 10 else 0)
df["Grade_11"] = df["Grade"].apply(lambda x: 1 if x == 11 else 0)
df["Grade_12"] = df["Grade"].apply(lambda x: 1 if x == 12 else 0)
df.drop(columns=["Grade"], inplace=True)

#Gênero(Gender)
df["Female"] = df["Gender"].apply(lambda x: 1 if x == "Female" else 0)
df["Male"] = df["Gender"].apply(lambda x: 1 if x == "Male" else 0)
df.drop(columns=["Gender"], inplace=True)

#Raça(Race)
df["Race_Asian"] = df["Race"].apply(lambda x: 1 if x == "Asian" else 0)
df["Race_Black"] = df["Race"].apply(lambda x: 1 if x == "Black" else 0)
df["Race_White"] = df["Race"].apply(lambda x: 1 if x == "White" else 0)
df["Race_Hispanic"] = df["Race"].apply(lambda x: 1 if x == "Hispanic" else 0)
df["Race_Other"] = df["Race"].apply(lambda x: 1 if x == "Other" else 0)
df["Race_Two_or_more"] = df["Race"].apply(lambda x: 1 if x == "Two-or-more" else 0)
df.drop(columns=["Race"], inplace=True)


#NívelSocieconomico(SES_Quartile)
df["SES_1_2"] = df["SES_Quartile"].apply(lambda x: 1 if 1 <= x <= 2 else 0)
df["SES_3_4"] = df["SES_Quartile"].apply(lambda x: 1 if 3 <= x <= 4 else 0)
df.drop(columns=["SES_Quartile"], inplace=True)


#EducaçãoParental(ParentalEducation)
df["PE_HS"] = df["ParentalEducation"].apply(lambda x: 1 if x == "HS" else 0)
df["PE_less_HS"] = df["ParentalEducation"].apply(lambda x: 1 if x == "<HS" else 0)
df["PE_Bachelors_plus"] = df["ParentalEducation"].apply(lambda x: 1 if x == "Bachelors+" else 0)
df["PE_SomeCollege"] = df["ParentalEducation"].apply(lambda x: 1 if x == "SomeCollege" else 0)
df.drop(columns=["ParentalEducation"], inplace=True)


#TipoEscola(SchoolType)
df["SchoolType_Public"] = df["SchoolType"].apply(lambda x: 1 if x == "Public" else 0)
df["SchoolType_Private"] = df["SchoolType"].apply(lambda x: 1 if x == "Private" else 0)
df.drop(columns=["SchoolType"], inplace=True)

#Localização(Locale)
df["Locale_Rural"] = df["Locale"].apply(lambda x: 1 if x == "Rural" else 0)
df["Locale_Town"] = df["Locale"].apply(lambda x: 1 if x == "Town" else 0)
df["Locale_Suburban"] = df["Locale"].apply(lambda x: 1 if x == "Suburban" else 0)
df["Locale_City"] = df["Locale"].apply(lambda x: 1 if x == "City" else 0)
df.drop(columns=["Locale"], inplace=True)


#Notas
df["TestScore_Math"] = df["TestScore_Math"].round(1)
df["TestScore_Reading"] = df["TestScore_Reading"].round(1)
df["TestScore_Science"] = df["TestScore_Science"].round(1)
df["GPA"] = df["GPA"].round(1)
df["Math_Low"] = df["TestScore_Math"].apply(lambda x: 1 if x < 60 else 0)
df["Math_Medium"] = df["TestScore_Math"].apply(lambda x: 1 if 60 <= x < 80 else 0)
df["Math_High"] = df["TestScore_Math"].apply(lambda x: 1 if x >= 80 else 0)
df["Reading_Low"] = df["TestScore_Reading"].apply(lambda x: 1 if x < 60 else 0)
df["Reading_Medium"] = df["TestScore_Reading"].apply(lambda x: 1 if 60 <= x < 80 else 0)
df["Reading_High"] = df["TestScore_Reading"].apply(lambda x: 1 if x >= 80 else 0)
df["Science_Low"] = df["TestScore_Science"].apply(lambda x: 1 if x < 60 else 0)
df["Science_Medium"] = df["TestScore_Science"].apply(lambda x: 1 if 60 <= x < 80 else 0)
df["Science_High"] = df["TestScore_Science"].apply(lambda x: 1 if x >= 80 else 0)
df["GPA_1"] = df["GPA"].apply(lambda x: 1 if 1<= x <2 else 0)
df["GPA_2"] = df["GPA"].apply(lambda x: 1 if 2<= x <3 else 0)
df["GPA_3"] = df["GPA"].apply(lambda x: 1 if 3<= x <4 else 0)
df["GPA_4"] = df["GPA"].apply(lambda x: 1 if 4<= x <5 else 0)
df.drop(columns=["TestScore_Math", "TestScore_Reading", "TestScore_Science", "GPA"], inplace=True)

#HorasEstudo(StudyHours)
df["StudyHours"] = df["StudyHours"].round(1)
df["StudyHours_0"] = df["StudyHours"].apply(lambda x: 1 if 0< x <1 else 0)
df["StudyHours_1"] = df["StudyHours"].apply(lambda x: 1 if 1<= x <2 else 0)
df["StudyHours_2"] = df["StudyHours"].apply(lambda x: 1 if x>=2 else 0)
df.drop(columns=["StudyHours"], inplace=True)

#Frequência(AttendanceRate)
df["AttendanceRate"] = (df["AttendanceRate"] * 100).round(1)
df["AttendanceRate_70"] = df["AttendanceRate"].apply(lambda x: 1 if 70<= x <80 else 0)
df["AttendanceRate_80"] = df["AttendanceRate"].apply(lambda x: 1 if 80<= x <90 else 0)
df["AttendanceRate_90"] = df["AttendanceRate"].apply(lambda x: 1 if 90<= x <100 else 0)
df["AttendanceRate_100"] = df["AttendanceRate"].apply(lambda x: 1 if x==100 else 0)
df.drop(columns=["AttendanceRate"], inplace=True)

#TempoLivre(FreeTime)
df["FreeTime_1_2"] = df["FreeTime"].apply(lambda x: 1 if 1 <= x <= 2 else 0)
df["FreeTime_3_4"] = df["FreeTime"].apply(lambda x: 1 if 3 <= x <= 4 else 0)
df["FreeTime_5"] = df["FreeTime"].apply(lambda x: 1 if x == 5 else 0)
df.drop(columns=["FreeTime"], inplace=True)


#Passeio(GoOut)
df["GoOut_1_2"] = df["GoOut"].apply(lambda x: 1 if 1 <= x <= 2 else 0)
df["GoOut_3_4"] = df["GoOut"].apply(lambda x: 1 if 3 <= x <= 4 else 0)
df["GoOut_5"] = df["GoOut"].apply(lambda x: 1 if x == 5 else 0)
df.drop(columns=["GoOut"], inplace=True)
#print(df.head())


#TESTE
pd.set_option('display.max_columns', None)
display(df.head(1))
#Seleção das colunas
#df_apriori = df[[
 #   "SchoolType",  #(0=Private/1=Public)
  #  "Math_Low",
   # "Math_Medium",
    #"Math_High"
#]]

#Transformação em booleano
#df_apriori = df_apriori.astype(bool)

#frequent_itemsets = apriori(df_apriori, min_support=0.1, use_colnames=True)
#rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)

#print(rules[["antecedents", "consequents", "support", "confidence", "lift"]])

,InternetAccess,Extracurricular,PartTimeJob,ParentSupport,Romantic,Age_14_15,Age_16_17,Age_18,Grade_9,Grade_10,Grade_11,Grade_12,Female,Male,Race_Asian,Race_Black,Race_White,Race_Hispanic,Race_Other,Race_Two_or_more,SES_1_2,SES_3_4,PE_HS,PE_less_HS,PE_Bachelors_plus,PE_SomeCollege,SchoolType_Public,SchoolType_Private,Locale_Rural,Locale_Town,Locale_Suburban,Locale_City,Math_Low,Math_Medium,Math_High,Reading_Low,Reading_Medium,Reading_High,Science_Low,Science_Medium,Science_High,GPA_1,GPA_2,GPA_3,GPA_4,StudyHours_0,StudyHours_1,StudyHours_2,AttendanceRate_70,AttendanceRate_80,AttendanceRate_90,AttendanceRate_100,FreeTime_1_2,FreeTime_3_4,FreeTime_5,GoOut_1_2,GoOut_3_4,GoOut_5
0,0,1,1,1,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
warnings.filterwarnings('ignore', category=DeprecationWarning)
gpa_columns = [
    "GPA_1", "GPA_2", "GPA_3", "GPA_4",
    "Locale_Rural", "Locale_Town", "Locale_Suburban", "Locale_City",
    "FreeTime_1_2", "FreeTime_3_4", "FreeTime_5",
    "SchoolType_Public", "SchoolType_Private",
    "AttendanceRate_70", "AttendanceRate_80", "AttendanceRate_90", "AttendanceRate_100",

    "GoOut_1_2", "GoOut_3_4", "GoOut_5",


]
df_gpa = df[gpa_columns]


#Teste com suporte 0.4

frequent_itemsets = fpgrowth(df_gpa, min_support = 0.4, use_colnames=True) # Reduced min_support
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
gpa_antecedents = ['GPA_1', 'GPA_2', 'GPA_3', 'GPA_4']
rules_gpa_as_antecedents = rules[rules['antecedents'].apply(lambda x: any(item in x for item in gpa_antecedents))]
rules_gpa_as_consequents = rules[rules['consequents'].apply(lambda x: any(item in x for item in gpa_antecedents))]
if not rules_gpa_as_antecedents.empty:
    display(rules_gpa_as_antecedents[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No association rules found for GPA antecedents with min_support=0.4 and min_threshold=1.0")

if not rules_gpa_as_consequents.empty:
  display(rules_gpa_as_consequents[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No rules found")

if not rules.empty:
  display(rules[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No rules found")

#Teste com suporte 0.5
frequent_itemsets = fpgrowth(df_gpa, min_support = 0.5, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
gpa_antecedents = ['GPA_1', 'GPA_2', 'GPA_3', 'GPA_4']
rules_gpa_as_antecedents = rules[rules['antecedents'].apply(lambda x: any(item in x for item in gpa_antecedents))]
rules_gpa_as_consequents = rules[rules['consequents'].apply(lambda x: any(item in x for item in gpa_antecedents))]
if not rules_gpa_as_antecedents.empty:
    display(rules_gpa_as_antecedents[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No association rules found for GPA antecedents with min_support=0.5 and min_threshold=1.0")

if not rules_gpa_as_consequents.empty:
  display(rules_gpa_as_consequents[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No rules found")

if not rules.empty:
  display(rules[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No rules found")

#Teste com suporte 0.6
frequent_itemsets = fpgrowth(df_gpa, min_support = 0.6, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
gpa_antecedents = ['GPA_1', 'GPA_2', 'GPA_3', 'GPA_4']
rules_gpa_as_antecedents = rules[rules['antecedents'].apply(lambda x: any(item in x for item in gpa_antecedents))]
rules_gpa_as_consequents = rules[rules['consequents'].apply(lambda x: any(item in x for item in gpa_antecedents))]
if not rules_gpa_as_antecedents.empty:
    display(rules_gpa_as_antecedents[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No association rules found for GPA antecedents with min_support=0.6 and min_threshold=1.0")

if not rules_gpa_as_consequents.empty:
  display(rules_gpa_as_consequents[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No rules found")

if not rules.empty:
  display(rules[["antecedents", "consequents", "support", "confidence", "lift"]])
else:
    print("No rules found")

No association rules found for GPA antecedents with min_support=0.4 and min_threshold=1.0
No rules found

           antecedents          consequents   support  confidence      lift
0  (SchoolType_Public)  (AttendanceRate_80)  0.402688    0.476879  1.000167
1  (AttendanceRate_80)  (SchoolType_Public)  0.402688    0.844565  1.000167
2  (SchoolType_Public)          (GoOut_1_2)  0.584519    0.692210  1.000498
3          (GoOut_1_2)  (SchoolType_Public)  0.584519    0.844845  1.000498

No association rules found for GPA antecedents with min_support=0.5 and min_threshold=1.0
No rules found

           antecedents          consequents   support  confidence      lift
0  (SchoolType_Public)          (GoOut_1_2)  0.584519    0.692210  1.000498
1          (GoOut_1_2)  (SchoolType_Public)  0.584519    0.844845  1.000498

No association rules found for GPA antecedents with min_support=0.6 and min_threshold=1.0
No rules found
No rules found